title: My blog
author: Jesus Manuel Lara Sanchez
email: larita19.jl@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  I am a Computer Science Engineerinterested in software design anddevelopment, 
  as well as continuing togrow personally and professionally, 
  Iam 26 years old and currently reside inthe city of Puebla.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: ManuLara19 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
